# Test-Editor/core/commands.py
# NOTE: This file is manually generated.

COMMAND_ARGS = {
    "StartAppWithLogin": ["username", "password", "secretKey"],
    "StartScenario": [],
    "EndScenario": [],
    "StopApp": [],
    # FWC Commands
    "FWC_VerifyText": ["text"],
    "FWC_ClickLink": ["link"],
    "FWC_DragDropElementRectangle": ["currentLocation", "targetLocation"],
    "FWC_VerifyTextNotPresent": ["text"],
    "FWC_ClickCell": ["cell"],
    "FWC_SetTextBox": ["textBox", "text"],
    "FWC_SelectWindow": ["window"],
    "FWC_SetRadioButton": ["radioButton"],
    "FWC_SetCheckBox": ["checkBox", "checkUncheck"],
    "FWC_SetDropdown": ["dropdown", "dropdownValue"],
    "FWC_PageRefresh": [],
    "FWC_VerifySelectedDropdownValue": ["dropdown", "dropdownValue"],
    "FWC_VerifyPageTitle": ["title"],
    "FWC_ClickButton": ["button"],
    "FWC_SelectToggleButton": ["toggleButton", "text"],
    "FWC_OpenURL": ["URL"],
    "FWC_OpenNewTab": ["url", "tabIndex"],
    "FWC_SwitchToTab": ["tabIndex"],
    "FWC_CloseTab": ["tabIndex"],
    "FWC_VerifyButtonExist": ["button"],
    "FWC_VerifyTextBoxExist": ["textBox"],
    "FWC_VerifyTextBoxNotExist": ["textBox"],
    "FWC_VerifyDropdownExist": ["dropdown"],
    "FWC_VerifyCheckBoxExist": ["checkBox"],
    "FWC_VerifyLinkExist": ["link"],
    "FWC_VerifyLabelExist": ["label"],
    "FWC_VerifyRadioButtonExist": ["radioButton"],
    "FWC_VerifyMultipleText": ["data"],
    "FWC_MouseOverLink": ["link"],
    "FWC_WaitForSecond": ["second"],
    "FWC_VerifyToggleButtonExist": ["toggleButton"],
    "FWC_RightClickOnCell": ["cell"],
    "FWC_DoubleClickOnCell": ["cell"],
    "FWC_RightClickOnCircle": ["circle"],
    "FWC_VerifyNegativeNumber": ["cell"],
    "FWC_VerifyPositiveNumber": ["cell"],
    "FWC_ScrollRight": [],
    "FWC_ScrollDown": [],
    "FWC_ScrollUp": [],
    "FWC_RightClickOnLabel": ["label"],
    "FWC_PressEnterKey": [],
    "FWC_ScrollLeft": [],
    "FWC_DoubleClickOnCircle": ["circle"],
    "FWC_AcceptAlert": [],
    "FWC_CancelAlert": [],
    "FWC_VerifyCheckBoxStatus": ["checkBox", "expectedStatus"],
    "FWC_VerifyButtonVisibleInTime": ["button"],
    "FWC_VerifyButtonClickableInTime": ["button"],
    "FWC_VerifyTextBoxVisibleInTime": ["textBox"],
    "FWC_VerifyDropdownVisibleInTime": ["dropdown"],
    "FWC_DragDropElement": ["dragLocation", "dropLocation"],
    "FWC_VerifyCheckBoxVisibleInTime": ["checkBox"],
    "FWC_VerifyLinkVisibleInTime": ["link"],
    "FWC_VerifyLabelVisibleInTime": ["label"],
    "FWC_VerifyZeroNotPresent": ["textBox"],
    "FWC_VerifyNeutralNumber": ["cell"],
    "FWC_VerifyRadioButtonVisibleInTime": ["radioButton"],
    "FWC_MultiActionsInput": ["elementNames", "elementValues"],
    "FWC_CloseAllWidgets": ["buttons"],
    "FWC_VerifyBidGreenColor": ["cell"],
    "FWC_VerifyButtonNotExist": ["button"],
    "FWC_ResizeWidget": [],
    "FWC_ScrollViewElement": ["button"],
    "FWC_CheckTitleAttribute": ["textBox"],
    "FWC_VerifyLabelNotExist": ["label"],
    "FWC_DragDropCellElement": ["dragLocation", "dropLocation"],
    "FWC_GenerateRandomAlphaNumeric": ["textBox"],
    "FWC_SelectFrame": ["frame"],
    "FWC_UnSelectFrame": [],
    "FWC_VerifyNonNegativeNumber": ["cell"],
    "FWC_ScrollViewElementTextBox": ["textBox"],
    "FWC_DoubleClickOnButton": ["button"],
    "FWC_VerifyToggleButtonNotExist": ["toggleButton"],
    "FWC_VerifyNumberExist": ["cell"],
    "FWC_MouseOverCircle": ["circle"],
    "FWC_MouseOverDropdown": ["dropdown"],
    "FWC_VerifyLinkNotExist": ["link"],
    "FWC_VerifyCheckBoxNotExist": ["checkBox"],
    "FWC_WaitForElementClickable": [],
    "FWC_MouseOverButton": ["button"],

    # EC Commands
    "EC_SetTextBoxRandomText": ["textBox", "appendTo", "length"],
    "EC_Login": ["username", "password", "secretKey"],
    "EC_EnterOTPText": ["otp_textbox", "otp_source"],
    "EC_SetDropdownAndEnter": ["dropdown", "dropdownValue"],
    "EC_SetTextBoxAndTab": ["textBox", "text"],
    "EC_SetTextBox": ["textBox", "text"],
    "EC_SelectDropdown": ["dropdown", "dropdownValue"],
    "EC_VerifyDropdownValue": ["dropdown", "dropdownValue"],
    "EC_VerifyToggleButtonValue": ["toggleButton", "toggleValue"],
    "EC_VerifyTextBoxValue": ["textBox", "textBoxValue"],
    "EC_VerifyCellData": ["cell", "cellValue"],
    "EC_VerifyCellValue": ["cell", "cellValue"],
    "EC_VerifyCellcolor": ["cell", "cellcolor"],
    "EC_OverrideSpot": ["text"],
    "EC_OverrideForward": ["text"],
    "EC_TakeScreenShot": [],
    "EC_SelectbyIndexvalue": ["index"],
    "EC_SetDeltaHedge": ["dropdownValue"],
    "EC_SetPremium": ["dropdownValue1", "dropdownValue2"],
    "EC_QuoteIdVerification": ["textBox", "cell"],
    "EC_VerifyTradeConfirmation": ["strategy", "verificationPoints"],
    "EC_VerifyQuoteRequest": ["strategy", "verificationPoints"],
    "EC_StoreRequestValue": ["strategy"],
    "EC_SelectLiquidityProvider": ["liquidityProvider"],
    "EC_QuoteIdInQuoteBlotters": ["textBox", "cell"],
    "EC_QuoteIdInPtt": ["textBox", "cell"],
    "EC_VerifyDropdownValueNotExist": ["dropdown", "dropdownValue"],
    "EC_TradeIdComparison": ["button1", "label", "button2"],
    "EC_VerifyAbsolutePremium": ["button1", "label1", "button2", "label2"],
    "EC_VerifyNegativeAbsolutePremium": ["label", "textBox"],
    "EC_VerifyRedColor": ["textBox"],
    "EC_VerifySolverAbosultePremium": ["textBox", "text"],
    "EC_LeiCodeVerifyinBlotters": ["textBox", "button", "cell"],
    "EC_VerifyAbsPremInConfirmation": ["textBox1", "button", "textBox2"],
    "EC_StpReportVerify": ["textBox", "button1", "button2", "cell"],
    "EC_ReinitializeClick": [],
    "EC_VerifyToggleButtonAbsent": ["toggleButton", "toggleValue"],
    "EC_CalculateDateFromToday": ["textbox", "period"],
    "EC_SetEventTime": ["textBox", "text"],
    "EC_CompareMidValues": ["cellIndexes1", "dropdown", "dropdownValue", "cellIndexes2"],
    "EC_CompareSpreadValues": ["cellIndexes1", "dropdown", "dropdownValue", "cellIndexes2", "parentId"],
    "EC_ExtractSpreadValues": ["cellIndexes", "parentId"],
    "EC_ExtractSkewValues": ["cellIndexes", "parentId"],
    "EC_ConfigurationMode": ["dropdown", "dropdownValue"],
    "EC_SetPrimusTextBoxAndTab": ["button", "parentId", "cellIndexes", "cellValues", "shouldCompare"],
    "EC_VerifyCompositeValues": ["controlData", "cellIndexes", "cellIndexes2", "weights", "sources"],
    "EC_EnterValuesInSkew": ["button", "parentId", "cellIndexes"],
    "EC_EnterValuesInSpread": ["button", "parentId", "cellIndexes"],
    "EC_ExtractMidRRBFTable": ["cellIndexes"],
    "EC_ExtractBidOfferRRBFTable": ["cellIndexes"],
    "EC_CalculateBidAndOffer": ["cellIndexes1", "cellIndexes2", "parentId", "toggleButton", "text"],
    "EC_SpotGridTicking": [],
    "EC_VerifyStrategyIdInTradeAnalytics": ["textBox", "button", "cell"],
    "EC_VerifyDataVolCurveChangeGrid": [],
    "EC_VerifyHedgeRateColor": ["textBox", "env"],
    "EC_VerifyCentryProcessesColor": ["Cell"],
    "EC_TradeConfirmationReportVerify": ["textBox", "button1", "button2", "cell"],
    "EC_DateVerification": ["textBox"],
    "EC_CompareDerivedToAggregate": ["cellIndexes1", "cellIndexes2", "strategy"],
    "EC_EnterValuesInCorrGrid": ["button", "strategy", "cellIndexes"],
    "EC_CalculateValuesInCorrGrid": ["strategy", "configuration", "cellIndexes"],
    "EC_CheckButtonNotClickable": ["button"],
    "EC_CompareBidOfferPrices": ["label1", "label2", "label3", "label4"],
    "EC_SetInvalidValuesInDropdown": ["dropdown", "dropdownValue"],
    "EC_SetVolTextBox": ["textBox", "text"],
    "EC_ResetBidOfferVerification": ["cellIndexes", "expectedBidValues"],
    "EC_ComapareToolTipPremium": ["labelsParam"],
    "EC_SetInvalidValuesInTextBox": ["textBox", "text"],
    "EC_VerifyLabelsMatch": ["label1", "button1", "button2", "label2"],
    "EC_VerifyAbsolutePremiumTradeConfo": ["button1", "label1", "button2", "label2"],
    "EC_SelectDate": [],
    "EC_VerifyCellContainsValue": ["cell", "cellValue"],
    "EC_VerifyTextBoxPlaceholder": ["textBox", "placeholderValue"],
    "EC_VerifyCallPutData": ["button"],
    "EC_VerifyForwardGridData": ["tenorParam"],
    "EC_LastLoginVerification": ["textBox"],
    "EC_DeleteExistingPage": ["label", "button1", "button2"],
    "EC_ValidateDailyVolWeighted": ["params"],
    "EC_HandlePopups": ["actionButton", "waitSeconds"],
}

# For backward compatibility, create the set of command names from the dictionary keys.
COMMANDS = set(COMMAND_ARGS.keys())
