COMMANDS = {
    "StartAppWithLogin": {},
    "StartScenario": {},
    "EndScenario": {},
    "StopApp": {},
    "FWC_SetTextBox": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyTextBoxExist": {"value1": "DATA1_COL"},
    "FWC_VerifyTextBoxNotExist": {"value1": "DATA1_COL"},
    "FWC_VerifyTextBoxVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_ScrollViewElementTextBox": {"value1": "DATA1_COL"},
    "FWC_GenerateRandomAlphaNumeric": {"value1": "DATA1_COL"},
    "FWC_VerifyZeroNotPresent": {"value1": "DATA1_COL"},
    "FWC_SetDropdown": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifySelectedDropdownValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyDropdownExist": {"value1": "DATA1_COL"},
    "FWC_VerifyDropdownVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_MouseOverDropdown": {"value1": "DATA1_COL"},
    "FWC_ClickButton": {"value1": "DATA1_COL"},
    "FWC_VerifyButtonExist": {"value1": "DATA1_COL"},
    "FWC_VerifyButtonNotExist": {"value1": "DATA1_COL"},
    "FWC_VerifyButtonVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_VerifyButtonClickableInTime": {"value1": "DATA1_COL"},
    "FWC_DoubleClickOnButton": {"value1": "DATA1_COL"},
    "FWC_ClickLink": {"value1": "DATA1_COL"},
    "FWC_VerifyLinkExist": {"value1": "DATA1_COL"},
    "FWC_VerifyLinkVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_MouseOverLink": {"value1": "DATA1_COL"},
    "FWC_VerifyLinkNotExist": {"value1": "DATA1_COL"},
    "FWC_SetCheckBox": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyCheckBoxExist": {"value1": "DATA1_COL"},
    "FWC_VerifyCheckBoxStatus": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyCheckBoxVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_VerifyCheckBoxNotExist": {"value1": "DATA1_COL"},
    "FWC_SetRadioButton": {"value1": "DATA1_COL"},
    "FWC_VerifyRadioButtonExist": {"value1": "DATA1_COL"},
    "FWC_VerifyRadioButtonVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_SelectToggleButton": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyToggleButtonExist": {"value1": "DATA1_COL"},
    "FWC_VerifyToggleButtonNotExist": {"value1": "DATA1_COL"},
    "FWC_VerifyText": {"value1": "DATA1_COL"},
    "FWC_VerifyTextNotPresent": {"value1": "DATA1_COL"},
    "FWC_VerifyMultipleText": {"value1": "DATA1_COL"},
    "FWC_DragDropElementRectangle": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_ClickCell": {"value1": "DATA1_COL"},
    "FWC_SelectWindow": {"value1": "DATA1_COL"},
    "FWC_PageRefresh": {},
    "FWC_VerifyPageTitle": {"value1": "DATA1_COL"},
    "FWC_OpenURL": {"value1": "DATA1_COL"},
    "FWC_OpenNewTab": {"value1": "DATA1_COL"},
    "FWC_SwitchToTab": {"value1": "DATA1_COL"},
    "FWC_CloseTab": {},
    "FWC_VerifyLabelExist": {"value1": "DATA1_COL"},
    "FWC_WaitForSecond": {"value1": "DATA1_COL"},
    "FWC_RightClickOnCell": {"value1": "DATA1_COL"},
    "FWC_DoubleClickOnCell": {"value1": "DATA1_COL"},
    "FWC_RightClickOnCircle": {"value1": "DATA1_COL"},
    "FWC_VerifyNegativeNumber": {"value1": "DATA1_COL"},
    "FWC_VerifyPositiveNumber": {"value1": "DATA1_COL"},
    "FWC_ScrollRight": {},
    "FWC_ScrollDown": {},
    "FWC_ScrollUp": {},
    "FWC_RightClickOnLabel": {"value1": "DATA1_COL"},
    "FWC_PressEnter": {},
    "FWC_ScrollLeft": {},
    "FWC_DoubleClickOnCircle": {"value1": "DATA1_COL"},
    "FWC_AcceptAlert": {},
    "FWC_CancelAlert": {},
    "FWC_DragDropElement": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_VerifyLabelVisibleInTime": {"value1": "DATA1_COL"},
    "FWC_VerifyNeutralNumber": {"value1": "DATA1_COL"},
    "FWC_MultiActionsInput": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_CloseAllWidgets": {"value1": "DATA1_COL"},
    "FWC_VerifyBidGreenColor": {"value1": "DATA1_COL"},
    "FWC_ResizeWidget": {},
    "FWC_ScrollViewElement": {"value1": "DATA1_COL"},
    "FWC_CheckTitleAttribute": {"value1": "DATA1_COL"},
    "FWC_VerifyLabelNotExist": {"value1": "DATA1_COL"},
    "FWC_DragDropCellElement": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "FWC_SelectFrame": {"value1": "DATA1_COL"},
    "FWC_UnSelectFrame": {},
    "FWC_VerifyNonNegativeNumber": {"value1": "DATA1_COL"},
    "FWC_VerifyNumberExist": {"value1": "DATA1_COL"},
    "FWC_MouseOverCircle": {"value1": "DATA1_COL"},
    "FWC_WaitForElementClickable": {},
    "EC_SetTextBoxRandomText": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SetTextBoxAndTab": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SetTextBox": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyTextBoxValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyTextBoxPlaceholder": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_CalculateDateFromToday": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SetEventTime": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SetPrimusTextBoxAndTab": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SetDropdownAndEnter": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SelectDropdown": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyDropdownValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SelectbyIndexvalue": {"value1": "DATA1_COL"},
    "EC_VerifyDropdownValueNotExist": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyToggleButtonValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyToggleButtonAbsent": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCellData": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCellValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCellContainsValue": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCellcolor": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_ExtractMidRRBFTable": {"value1": "DATA1_COL"},
    "EC_ExtractBidOfferRRBFTable": {"value1": "DATA1_COL"},
    "EC_EnterValuesInCorrGrid": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_CalculateValuesInCorrGrid": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_Login": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_EnterOTPText": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_OverrideSpot": {"value1": "DATA1_COL"},
    "EC_OverrideForward": {"value1": "DATA1_COL"},
    "EC_TakeScreenShot": {"value1": "DATA1_COL"},
    "EC_SetDeltaHedge": {"value1": "DATA1_COL"},
    "EC_SetPremium": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_QuoteIdVerification": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyTradeConfirmation": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyQuoteRequest": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_StoreRequestValue": {"value1": "DATA1_COL"},
    "EC_SelectLiquidityProvider": {"value1": "DATA1_COL"},
    "EC_QuoteIdInQuoteBlotters": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_QuoteIdInPtt": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_TradeIdComparison": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyAbsolutePremium": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyNegativeAbsolutePremium": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyRedColor": {"value1": "DATA1_COL"},
    "EC_VerifySolverAbosultePremium": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_LeiCodeVerifyinBlotters": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyAbsPremInConfirmation": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_StpReportVerify": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_ReinitializeClick": {},
    "EC_CompareMidValues": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_CompareSpreadValues": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_ExtractSpreadValues": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_ExtractSkewValues": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_ConfigurationMode": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCompositeValues": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_EnterValuesInSkew": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_EnterValuesInSpread": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_CalculateBidAndOffer": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_SpotGridTicking": {},
    "EC_VerifyStrategyIdInTradeAnalytics": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyDataVolCurveChangeGrid": {},
    "EC_VerifyHedgeRateColor": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_VerifyCentryProcessesColor": {"value1": "DATA1_COL"},
    "EC_TradeConfirmationReportVerify": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_DateVerification": {"value1": "DATA1_COL"},
    "EC_CompareDerivedToAggregate": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_CheckButtonNotClickable": {"value1": "DATA1_COL"},
    "EC_CompareBidOfferPrices": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
    "EC_HandlePopups": {"value1": "DATA1_COL", "value2": "DATA2_COL"},
}