from .commands import COMMANDS

STEPS_PERFORMED = {
    "STARTSCENARIO": "Scenario Started",
    "ENDSCENARIO": "Scenario Ended",
    "FWC_CLICKBUTTON": "Click on {value1} button",
    "FWC_CLICKLINK": "Click on {value1} link",
    "EC_VERIFYDROPDOWNVALUE": "Verify {value2} in {value1} dropdown",
    "EC_VERIFYTOGGLEBUTTONVALUE": "Verify {value2} in {value1} toggle",
    "EC_SETDROPDOWNANDENTER": "Set {value2} in {value1} dropdown",
    "EC_SELECTDROPDOWN": "Set {value2} in {value1} dropdown",
    "EC_SETINVALIDVALUESINDROPDOWN": "Set {value2} in {value1} dropdown",
    "FWC_VERIFYTEXT": "Verify {value1} text is present",
    "FWC_SETTEXTBOX": "Set {value2} in {value1} text box",
    "EC_SETTEXTBOXANDTAB": "Set {value2} in {value1} text box",
    "EC_SETTEXTBOX": "Set {value2} in {value1} text box",
    "EC_SETINVALIDVALUESINTEXTBOX": "Set {value2} in {value1} text box",
    "FWC_DRAGDROPELEMENTRECTANGLE": "Drag and drop the {value1}",
    "FWC_VERIFYTEXTNOTPRESENT": "Verify {value1} text is not present",
    "FWC_CLICKCELL": "Click on {value1} cell",
    "FWC_SETCHECKBOX": "{value2} the {value1} checkbox",
    "FWC_SETDROPDOWN": "Set {value2} in {value1} dropdown",
    "FWC_PAGEREFRESH": "Refresh the page",
    "FWC_SELECTTOGGLEBUTTON": "Select {value2} in {value1} toggle",
    "FWC_OPENNEWTAB": "Open a new tab",
    "FWC_SWITCHTOTAB": "Switch to tab {value1}",
    "FWC_VERIFYBUTTONEXIST": "Verify {value1} button exists",
    "FWC_VERIFYTEXTBOXEXIST": "Verify {value1} textbox exists",
    "FWC_VERIFYTEXTBOXNOTEXIST": "Verify {value1} textbox does not exist",
    "FWC_VERIFYDROPDOWNEXIST": "Verify {value1} dropdown exists",
    "FWC_VERIFYCHECKBOXEXIST": "Verify {value1} checkbox exists",
    "FWC_VERIFYLINKEXIST": "Verify {value1} link exists",
    "FWC_VERIFYLABELEXIST": "Verify {value1} label exists",
    "FWC_MOUSEOVERLINK": "Mouse over to {value1} link",
    "FWC_WAITFORSECOND": "Wait for a few seconds",
    "FWC_VERIFYTOGGLEBUTTONEXIST": "Verify toggle button {value1} exists",
    "FWC_RIGHTCLICKONCELL": "Right-click on cell in {value1}",
    "FWC_DOUBLECLICKONCELL": "Double-click on cell in {value1}",
    "FWC_RIGHTCLICKONCIRCLE": "Right-click on circle in {value1}",
    "FWC_VERIFYNEGATIVENUMBER": "Verify it is a negative number",
    "FWC_VERIFYPOSITIVENUMBER": "Verify it is a positive number",
    "FWC_SCROLLRIGHT": "Do scroll right",
    "FWC_SCROLLDOWN": "Do scroll down",
    "FWC_SCROLLUP": "Do scroll up",
    "FWC_RIGHTCLICKONLABEL": "Right-click on label {value1}",
    "FWC_SCROLLLEFT": "Do scroll left",
    "FWC_DOUBLECLICKONCIRCLE": "Double-click on circle in {value1}",
    "FWC_VERIFYCHECKBOXSTATUS": "Verify the checkbox is {value2} in {value1} checkbox",
    "FWC_DRAGDROPELEMENT": "Drag and drop the {value1}",
    "FWC_SELECTFRAME": "Select the frame",
    "FWC_UNSELECTFRAME": "UnSelect the frame",
    "FWC_VERIFYTOGGLEBUTTONNOTEXIST": "Verify toggle button {value1} does not exist",
    "FWC_DOUBLECLICKONBUTTON": "Double-click on {value1} button",
    "FWC_VERIFYNONNEGATIVENUMBER": "Verify number is non-negative",
    "FWC_VERIFYZERONOTPRESENT": "Verify zero is not present",
    "FWC_GENERATERANDOMALPHANUMERIC": "Generate random text",
    "FWC_SCROLLVIEWELEMENTTEXTBOX": "Scroll to view the element",
    "EC_LOGIN": "Login by entering username, password, and OTP",
    "EC_VERIFYTEXTBOXVALUE": "Verify {value2} in {value1} textbox",
    "EC_VERIFYCELLDATA": "Verify {value2} in {value1} cell",
    "EC_VERIFYCELLVALUE": "Verify {value2} in {value1} cell",
    "EC_TAKESCREENSHOT": "Take a screenshot",
    "EC_VERIFYDROPDOWNVALUENOTEXIST": "Verify {value2} in {value1} dropdown does not exist",
    "EC_REINITIALIZECLICK": "Click on reinitialize button",
    "EC_VERIFYTOGGLEBUTTONABSENT": "Verify {value2} in {value1} toggle does not exist",
}

def get_steps_performed(command, value1, value2):
    """
    Generates steps performed messages based on the provided command, value1, and value2.
    """
    command = command.upper()
    if command in STEPS_PERFORMED:
        return STEPS_PERFORMED[command].format(value1=value1, value2=value2)
    return ""
