from .commands import COMMANDS

STEPS_PERFORMED = {
    "STARTSCENARIO": "Scenario Started",
    "ENDSCENARIO": "Scenario Ended",
    "FWC_CLICKBUTTON": "Click on {value1} button",
    "FWC_CLICKLINK": "Click on {value1} link",
    "EC_VERIFYDROPDOWNVALUE": "Verify {value2} in {value1} dropdown",
    "EC_VERIFYTOGGLEBUTTONVALUE": "Verify {value2} in {value1} toggle",
    "EC_SETDROPDOWNANDENTER": "Set {value2} in {value1} dropdown and enter",
    "EC_SELECTDROPDOWN": "Select {value2} in {value1} dropdown",
    "EC_SETINVALIDVALUESINDROPDOWN": "Set invalid value {value2} in {value1} dropdown",
    "FWC_VERIFYTEXT": "Verify {value1} text is present",
    "FWC_SETTEXTBOX": "Set {value2} in {value1} text box",
    "EC_SETTEXTBOXANDTAB": "Set {value2} in {value1} text box and tab",
    "EC_SETTEXTBOX": "Set {value2} in {value1} text box",
    "EC_SETINVALIDVALUESINTEXTBOX": "Set invalid value {value2} in {value1} text box",
    "FWC_DRAGDROPELEMENTRECTANGLE": "Drag and drop {value1} to {value2}",
    "FWC_VERIFYTEXTNOTPRESENT": "Verify {value1} text is not present",
    "FWC_CLICKCELL": "Click on {value1} cell",
    "FWC_SETCHECKBOX": "{value2} the {value1} checkbox",
    "FWC_SETDROPDOWN": "Set {value2} in {value1} dropdown",
    "FWC_PAGEREFRESH": "Refresh the page",
    "FWC_SELECTTOGGLEBUTTON": "Select {value2} in {value1} toggle",
    "FWC_OPENNEWTAB": "Open new tab with URL {value1} and name {value2}",
    "FWC_SWITCHTOTAB": "Switch to tab {value1}",
    "FWC_VERIFYBUTTONEXIST": "Verify {value1} button exists",
    "FWC_VERIFYTEXTBOXEXIST": "Verify {value1} textbox exists",
    "FWC_VERIFYTEXTBOXNOTEXIST": "Verify {value1} textbox does not exist",
    "FWC_VERIFYDROPDOWNEXIST": "Verify {value1} dropdown exists",
    "FWC_VERIFYCHECKBOXEXIST": "Verify {value1} checkbox exists",
    "FWC_VERIFYLINKEXIST": "Verify {value1} link exists",
    "FWC_VERIFYLABELEXIST": "Verify {value1} label exists",
    "FWC_MOUSEOVERLINK": "Mouse over to {value1} link",
    "FWC_WAITFORSECOND": "Wait for {value1} seconds",
    "FWC_VERIFYTOGGLEBUTTONEXIST": "Verify toggle button {value1} exists",
    "FWC_RIGHTCLICKONCELL": "Right-click on cell in {value1}",
    "FWC_DOUBLECLICKONCELL": "Double-click on cell in {value1}",
    "FWC_RIGHTCLICKONCIRCLE": "Right-click on circle in {value1}",
    "FWC_VERIFYNEGATIVENUMBER": "Verify {value1} is a negative number",
    "FWC_VERIFYPOSITIVENUMBER": "Verify {value1} is a positive number",
    "FWC_SCROLLRIGHT": "Do scroll right",
    "FWC_SCROLLDOWN": "Do scroll down",
    "FWC_SCROLLUP": "Do scroll up",
    "FWC_RIGHTCLICKONLABEL": "Right-click on label {value1}",
    "FWC_SCROLLLEFT": "Do scroll left",
    "FWC_DOUBLECLICKONCIRCLE": "Double-click on circle in {value1}",
    "FWC_VERIFYCHECKBOXSTATUS": "Verify the checkbox is {value2} in {value1} checkbox",
    "FWC_DRAGDROPELEMENT": "Drag and drop {value1} to {value2}",
    "FWC_SELECTFRAME": "Select frame {value1}",
    "FWC_UNSELECTFRAME": "Unselect the frame",
    "FWC_VERIFYTOGGLEBUTTONNOTEXIST": "Verify toggle button {value1} does not exist",
    "FWC_DOUBLECLICKONBUTTON": "Double-click on {value1} button",
    "FWC_VERIFYNONNEGATIVENUMBER": "Verify {value1} is a non-negative number",
    "FWC_VERIFYZERONOTPRESENT": "Verify zero is not present in {value1}",
    "FWC_GENERATERANDOMALPHANUMERIC": "Generate random alphanumeric text in {value1}",
    "FWC_SCROLLVIEWELEMENTTEXTBOX": "Scroll to view the element {value1}",
    "EC_LOGIN": "Login with username {value1}",
    "EC_VERIFYTEXTBOXVALUE": "Verify {value2} in {value1} textbox",
    "EC_VERIFYCELLDATA": "Verify {value2} in {value1} cell",
    "EC_VERIFYCELLVALUE": "Verify {value2} in {value1} cell",
    "EC_TAKESCREENSHOT": "Take a screenshot",
    "EC_VERIFYDROPDOWNVALUENOTEXIST": "Verify {value2} in {value1} dropdown does not exist",
    "EC_REINITIALIZECLICK": "Click on reinitialize button",
    "EC_VERIFYTOGGLEBUTTONABSENT": "Verify {value2} in {value1} toggle does not exist",
    "FWC_VERIFYTEXTBOXVISIBLEINTIME": "Verify {value1} textbox is visible within a specified time",
    "FWC_VERIFYSELECTEDDROPDOWNVALUE": "Verify selected dropdown value of {value1} is {value2}",
    "FWC_VERIFYDROPDOWNVISIBLEINTIME": "Verify {value1} dropdown is visible within a specified time",
    "FWC_MOUSEOVERDROPDOWN": "Mouse over to {value1} dropdown",
    "FWC_VERIFYBUTTONNOTEXIST": "Verify {value1} button does not exist",
    "FWC_VERIFYBUTTONVISIBLEINTIME": "Verify {value1} button is visible within a specified time",
    "FWC_VERIFYBUTTONCLICKABLEINTIME": "Verify {value1} button is clickable within a specified time",
    "FWC_VERIFYLINKVISIBLEINTIME": "Verify {value1} link is visible within a specified time",
    "FWC_VERIFYLINKNOTEXIST": "Verify {value1} link does not exist",
    "FWC_VERIFYCHECKBOXNOTEXIST": "Verify {value1} checkbox does not exist",
    "FWC_VERIFYCHECKBOXVISIBLEINTIME": "Verify {value1} checkbox is visible within a specified time",
    "FWC_SETRADIOBUTTON": "Set radio button {value1}",
    "FWC_VERIFYRADIOBUTTONEXIST": "Verify {value1} radio button exists",
    "FWC_VERIFYRADIOBUTTONVISIBLEINTIME": "Verify {value1} radio button is visible within a specified time",
    "FWC_VERIFYMULTIPLETEXT": "Verify multiple text {value1}",
    "FWC_SELECTWINDOW": "Select window with title {value1}",
    "FWC_VERIFYPAGETITLE": "Verify page title is {value1}",
    "FWC_OPENURL": "Open URL {value1}",
    "FWC_CLOSETAB": "Close tab {value1}",
    "FWC_PRESSENTER": "Press enter key",
    "FWC_ACCEPTALERT": "Accept the alert",
    "FWC_CANCELALERT": "Cancel the alert",
    "FWC_VERIFYLABELVISIBLEINTIME": "Verify {value1} label is visible within a specified time",
    "FWC_VERIFYNEUTRALNUMBER": "Verify {value1} is a neutral number",
    "FWC_MULTIACTIONSINPUT": "Perform multi-actions input on {value1} with values {value2}",
    "FWC_CLOSEALLWIDGETS": "Close all widgets with name {value1}",
    "FWC_VERIFYBIDGREENCOLOR": "Verify bid green color for {value1}",
    "FWC_RESIZEWIDGET": "Resize the widget",
    "FWC_SCROLLVIEWELEMENT": "Scroll to view element {value1}",
    "FWC_CHECKTITLEATTRIBUTE": "Check title attribute of {value1}",
    "FWC_VERIFYLABELNOTEXIST": "Verify {value1} label does not exist",
    "FWC_DRAGDROPCELLELEMENT": "Drag and drop cell element {value1} to {value2}",
    "FWC_VERIFYNUMBEREXIST": "Verify number {value1} exists",
    "FWC_MOUSEOVERCIRCLE": "Mouse over to {value1} circle",
    "FWC_WAITFORELEMENTCLICKABLE": "Wait for element to be clickable",
    "EC_SETTEXTBOXRANDOMTEXT": "Set random text in {value1} with prefix {value2}",
    "EC_VERIFYTEXTBOXPLACEHOLDER": "Verify placeholder of {value1} is {value2}",
    "EC_CALCULATEDATEFROMTODAY": "Calculate date from today and set in {value1} with days {value2}",
    "EC_SETEVENTTIME": "Set event time in {value1} with time {value2}",
    "EC_SETPRIMUSTEXTBOXANDTAB": "Set primus textbox {value1} with value {value2}",
    "EC_SELECTBYINDEXVALUE": "Select by index value {value1}",
    "EC_VERIFYCELLCONTAINSVALUE": "Verify cell {value1} contains value {value2}",
    "EC_VERIFYCELLCOLOR": "Verify cell {value1} color is {value2}",
    "EC_EXTRACTMIDRRBFTABLE": "Extract mid from RR/BF table {value1}",
    "EC_EXTRACTBIDOFFERRRBFTABLE": "Extract bid/offer from RR/BF table {value1}",
    "EC_ENTERVALUESINCORRGRID": "Enter values in correlation grid {value1} with value {value2}",
    "EC_CALCULATEVALUESINCORRGRID": "Calculate values in correlation grid {value1} with value {value2}",
    "EC_ENTEROTPTEXT": "Enter OTP text in {value1}",
    "EC_OVERRIDESPOT": "Override spot with value {value1}",
    "EC_OVERRIDEFORWARD": "Override forward with value {value1}",
    "EC_SETDELTAHEDGE": "Set delta hedge with value {value1}",
    "EC_SETPREMIUM": "Set premium {value1} with value {value2}",
    "EC_QUOTEIDVERIFICATION": "Verify quote ID {value1} from source {value2}",
    "EC_VERIFYTRADECONFIRMATION": "Verify trade confirmation for {value1} with message {value2}",
    "EC_VERIFYQUOTEREQUEST": "Verify quote request for {value1} with message {value2}",
    "EC_STOREREQUESTVALUE": "Store request value for {value1}",
    "EC_SELECTLIQUIDITYPROVIDER": "Select liquidity provider {value1}",
    "EC_QUOTEIDINQUOTEBLOTTERS": "Verify quote ID {value1} in quote blotters of type {value2}",
    "EC_QUOTEIDINPTT": "Verify quote ID {value1} in PTT of type {value2}",
    "EC_TRADEIDCOMPARISON": "Compare trade ID {value1} with {value2}",
    "EC_VERIFYABSOLUTEPREMIUM": "Verify absolute premium for {value1} is {value2}",
    "EC_VERIFYNEGATIVEABSOLUTEPREMIUM": "Verify negative absolute premium for {value1} is {value2}",
    "EC_VERIFYREDCOLOR": "Verify red color for {value1}",
    "EC_VERIFYSOLVERABOSULTEPREMIUM": "Verify solver absolute premium for {value1} is {value2}",
    "EC_LEICODEVERIFYINBLOTTERS": "Verify LEI code {value1} in blotters of type {value2}",
    "EC_VERIFYABSPREMINCONFIRMATION": "Verify absolute premium in confirmation for {value1} with type {value2}",
    "EC_STPREPORTVERIFY": "Verify STP report for {value1} with type {value2}",
    "EC_COMPAREMIDVALUES": "Compare mid values for {value1} and {value2}",
    "EC_COMPARESPREADVALUES": "Compare spread values for {value1} and {value2}",
    "EC_EXTRACTSPREADVALUES": "Extract spread values from {value1} to {value2}",
    "EC_EXTRACTSKEWVALUES": "Extract skew values from {value1} to {value2}",
    "EC_CONFIGURATIONMODE": "Handle configuration mode {value1} with action {value2}",
    "EC_VERIFYCOMPOSITEVALUES": "Verify composite values for {value1} and {value2}",
    "EC_ENTERVALUESINSKEW": "Enter values in skew {value1} with value {value2}",
    "EC_ENTERVALUESINSPREAD": "Enter values in spread {value1} with value {value2}",
    "EC_CALCULATEBIDANDOFFER": "Calculate bid and offer for {value1} and {value2}",
    "EC_SPOTGRIDTICKING": "Verify spot grid is ticking",
    "EC_VERIFYSTRATEGYIDINTRADEANALYTICS": "Verify strategy ID {value1} in trade analytics of type {value2}",
    "EC_VERIFYDATAVOLCURVECHANGEGRID": "Verify data in vol curve change grid",
    "EC_VERIFYHEDGERATECOLOR": "Verify hedge rate color for {value1} is {value2}",
    "EC_VERIFYCENTRYPROCESSESCOLOR": "Verify centry processes color for {value1}",
    "EC_TRADECONFIRMATIONREPORTVERIFY": "Verify trade confirmation report for {value1} with type {value2}",
    "EC_DATEVERIFICATION": "Verify date {value1}",
    "EC_COMPAREDERIVEDTOAGGREGATE": "Compare derived value {value1} to aggregate value {value2}",
    "EC_CHECKBUTTONNOTCLICKABLE": "Check button {value1} is not clickable",
    "EC_COMPAREBIDOFFERPRICES": "Compare bid and offer prices for {value1} and {value2}",
    "EC_HANDLEPOPUPS": "Handle popup",
    "EC_SETINVALIDVALUESINDROPDOWN": "Attempt to set invalid value(s) in {value1} dropdown",
    "EC_SETVOLTEXTBOX": "Set {value2} in {value1} vol textbox",
    "EC_RESETBIDOFFERVERIFICATION": "Verify bid/offer reset for cells {value1} with expected bids {value2}",
    "EC_COMAPARETOOLTIPPREMIUM": "Compare tooltip premium for labels {value1}",
    "EC_SETINVALIDVALUESINTEXTBOX": "Attempt to set invalid value(s) in {value1} textbox",
    "EC_VERIFYLABELSMATCH": "Verify labels match",
    "EC_VERIFYABSOLUTEPREMIUMTRADECONFO": "Verify absolute premium in trade confirmation",
    "EC_SELECTDATE": "Select a date from the calendar",
    "EC_VERIFYCALLPUTDATA": "Verify call/put data",
    "EC_VERIFYFORWARDGRIDDATA": "Verify forward grid data for tenors {value1}",
    "EC_LASTLOGINVERIFICATION": "Verify last login timestamp for {value1}",
    "EC_DELETEEXISTINGPAGE": "Delete existing page",
    "EC_VALIDATEDAILYVOLWEIGHTED": "Validate daily vol weighted",
    "FWC_VERIFYBUTTONTEXT": "Verify {value1} button text is {value2}",
    "FWC_GETELEMENTTEXT": "Get text from {value1}",
    "FWC_VERIFYBULKDATA": "Verify bulk data {value1}",
    "FWC_SETTLEPRICINGSCREEN": "Settle pricing screen",
    "FWC_WAITFORELEMENTTOBEINTERACTABLE": "Wait for element to be interactable",
    "FWC_MOUSEOVERBUTTON": "Mouse over {value1} button",
}

def get_steps_performed(command, value1, value2):
    command = command.upper()
    if command in STEPS_PERFORMED:
        return STEPS_PERFORMED[command].format(value1=value1, value2=value2)
    return ""
